### PR TITLE
fix!: don't force a version of @cdktf/provider-project

### LINKED ISSUE #262: Incorrectly injecting the version into projen
I noticed that the version of `cdktf-provider-project` that is used by `package.json` is an [old version](https://github.com/cdktf/cdktf-provider-github/blob/main/package.json#L46) and does not match the [locked version](https://github.com/cdktf/cdktf-provider-github/blob/main/yarn.lock#L104). This has been fine, because [the semver constraint allows it](https://jubianchi.github.io/semver-check/#/^0.2.8/0.2.65), but it will cause a problem when either the [major](https://jubianchi.github.io/semver-check/#/^0.2.8/1.0.0) or [minor](https://jubianchi.github.io/semver-check/#/^0.2.8/0.3.0) version of this project gets bumped.

This happens because the [project generator loads from](https://github.com/cdktf/cdktf-provider-project/blob/main/src/index.ts#L14) `version.json`, which was correct until projen [updated the bump task](https://github.com/cdktf/cdktf-provider-project/blob/main/.projen/tasks.json#L31) to instead write the version into `package.json` and abandoned `version.json`.

### PR DESCRIPTION
**Pull request by rlmartin**
Fixes #262

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -123,7 +121,7 @@ export class CdktfProviderProject extends cdk.JsiiProject {
       license: "MPL-2.0",
       releaseToNpm: true,
       minNodeVersion,
-      devDeps: [`@cdktf/provider-project@^${version}`, "dot-prop@^5.2.0"],
+      devDeps: ["dot-prop@^5.2.0", ...(options.devDeps ?? [])],
```
Comment (ansgarm) [inline src/index.ts:124]: Quick question, as I haven't checked how Projen handles this, but does this now require us to set a peer dependency on the provider project in the `projenrc.js` file that sets this up?
If yes, we should update our tests to do so, too. We also need to remember this change when we roll it out and change that for each of our pre-built providers as well (there's a single [template](https://github.com/cdktf/cdktf-repository-manager/blob/main/projenrc.template.js) file, that helps with that).

Comment (rlmartin) [reply src/index.ts:124]: I'll admit that my knowledge around peer dependencies is a bit thin. My gut is 'no', because you could always switch to a completely different project type - or even a fork of the came project type but with a different name. If the peer dependency doesn't complicate or prevent such changes, I could see it working. Otherwise, maybe it remains intentionally loose; at the very least you have everything in the same `.projenrc.js` file: the dependency _and_ the one time it gets imported.

**Comment by ansgarm** [comment]
Hi @rlmartin 👋
Given that this has been in the air for quite some time: Is this still an issue or shall we close this PR?

File: src/index.ts (hunk 1 above)
Comment (ansgarm) [reply src/index.ts]: Yeah, setting the `devDependency` on the Projen project used seems like the right thing to do. Fyi: I pushed a commit that changes our tests to do so, too, to make it more explicit how this Projen project should be used.

**Comment by ansgarm** [comment]
I agree 👍

I rebased your branch and adjusted one test case – I'll put in a PR in the template in our repository-manager to ensure our pre-built providers set the dev dependency on their own for the future 👍

After that PR is merged, we can merge and release this change.

**Review by ansgarm — APPROVED** [review]

**Comment by rlmartin** [comment]
Thanks - sounds great! I'll leave it to you to merge when appropriate.

**Comment by ansgarm** [comment]
I asked for another review from the team, but as far as I'm concerned, this can be merged now 👍

**Review by DanielMSchmidt — APPROVED** [review]
